### ISSUE TITLE
Líbrerías no estándar

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-code_arcade#10]
Hola,

Salvo excepciones justificadas previamente acordadas conmigo, debéis evitar el uso de librerías no estándar. Estas librerías impiden la [portabilidad del código](https://es.wikipedia.org/wiki/Portabilidad). 

En particular, el código del juego pong emplea la librería `windows.h`:
https://github.com/aigora/twIE_2021-code_arcade/blob/d97fcb75ba8d30c6330959c6db6a9da6e6b8dcf4/pong.c#L3

**Comment by nicoascastrogarcia** [comment]
Esa librería la voy a borrar porque la función que quería meter hacía que el programa no funcionase, así que solo tengo que borrarla. Lo que si tenía una pregunta, como hago para meter un programa dentro de otro, porque he visto que se hace poniendo la dirección en tu ordenador pero cada uno lo tiene guardado en un sitio distinto y quería saber si hay alguna forma de hacerlo
