### ISSUE TITLE
Menú del programa

### ISSUE THREAD

**Issue by lquintanac** [aigora/twIE_2021-code_arcade#2]
Debéis generar código que implemente un **menú provisional** con el que el usuario de vuestro programa debe interactuar. Este menú debe contener las opciones necesarias para acceder a las funcionalidades previstas, aunque aún no realizará ninguna acción. 
El menú estará implementado mediante un bucle `switch-case` y se repetirá indefinidamente hasta que el usuario decida salir del programa.

**Comment by oscarperpinan** [comment]
Os habéis limitado a crear un menú que no es más que un esqueleto sin contenido. Al menos deberían aparecer las funciones que luego se usarán, o comentarios en cada `case` para indicar lo que ocurrirá.
